# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['../start_taskman.py'],
    pathex=['..'],
    binaries=[],
    datas=[
        ('../data', 'data'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.asyncio',
        'uvicorn.loops.uvloop',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.websockets_impl',
        'uvicorn.protocols.websockets.wsproto_impl',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.websockets',
        'sqlalchemy',
        'sqlalchemy.ext.asyncio',
        'sqlalchemy.dialects.postgresql.asyncpg',
        'asyncpg',
        'asyncpg.protocol.protocol',
        'asyncpg.pgproto.pgproto',
        'pydantic',
        'pydantic_core',
        'pydantic_settings',
        'grpc',
        'grpc._cython.cygrpc',
        'google.protobuf.internal.builder',
        'anyio',
        'anyio._backends._asyncio',
        'anyio._backends._trio',
        'httptools',
        'uvloop',
        'websockets',
        'h11',
        'blueprints',
        'blueprints.models',
        'blueprints.router',
        'blueprints.schemas',
        'blueprints.service',
        'core',
        'core.config',
        'core.database',
        'core.grpc_client',
        'grpc_gen',
        'grpc_gen.job_runner_pb2',
        'grpc_gen.job_runner_pb2_grpc',
        'jobs',
        'jobs.models',
        'jobs.router',
        'jobs.schemas',
        'jobs.service',
        'jobs.ws_manager',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter'],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='taskman',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='taskman',
)
