# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_gen import job_runner_pb2 as job__runner__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in job_runner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RDSJobRunnerStub(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/job_runner.RDSJobRunner/Ping',
                request_serializer=job__runner__pb2.PingRequest.SerializeToString,
                response_deserializer=job__runner__pb2.PingResponse.FromString,
                _registered_method=True)
        self.execute = channel.unary_unary(
                '/job_runner.RDSJobRunner/execute',
                request_serializer=job__runner__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=job__runner__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.library = channel.unary_unary(
                '/job_runner.RDSJobRunner/library',
                request_serializer=job__runner__pb2.LibraryRequest.SerializeToString,
                response_deserializer=job__runner__pb2.LibraryResponse.FromString,
                _registered_method=True)
        self.jobs = channel.unary_unary(
                '/job_runner.RDSJobRunner/jobs',
                request_serializer=job__runner__pb2.JobsRequest.SerializeToString,
                response_deserializer=job__runner__pb2.JobsResponse.FromString,
                _registered_method=True)
        self.trigger = channel.unary_unary(
                '/job_runner.RDSJobRunner/trigger',
                request_serializer=job__runner__pb2.TriggerRequest.SerializeToString,
                response_deserializer=job__runner__pb2.TriggerResponse.FromString,
                _registered_method=True)
        self.abort = channel.unary_unary(
                '/job_runner.RDSJobRunner/abort',
                request_serializer=job__runner__pb2.AbortRequest.SerializeToString,
                response_deserializer=job__runner__pb2.AbortResponse.FromString,
                _registered_method=True)
        self.status = channel.unary_unary(
                '/job_runner.RDSJobRunner/status',
                request_serializer=job__runner__pb2.StatusRequest.SerializeToString,
                response_deserializer=job__runner__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/job_runner.RDSJobRunner/StreamStatus',
                request_serializer=job__runner__pb2.StatusStreamRequest.SerializeToString,
                response_deserializer=job__runner__pb2.StatusUpdate.FromString,
                _registered_method=True)


class RDSJobRunnerServicer(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def library(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def jobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def trigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """NEW: task_manager opens this stream after execute().
        Runner pushes StatusUpdate messages until the job finishes.
        Replaces the old REST PUT callback pattern.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RDSJobRunnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=job__runner__pb2.PingRequest.FromString,
                    response_serializer=job__runner__pb2.PingResponse.SerializeToString,
            ),
            'execute': grpc.unary_unary_rpc_method_handler(
                    servicer.execute,
                    request_deserializer=job__runner__pb2.ExecuteRequest.FromString,
                    response_serializer=job__runner__pb2.ExecuteResponse.SerializeToString,
            ),
            'library': grpc.unary_unary_rpc_method_handler(
                    servicer.library,
                    request_deserializer=job__runner__pb2.LibraryRequest.FromString,
                    response_serializer=job__runner__pb2.LibraryResponse.SerializeToString,
            ),
            'jobs': grpc.unary_unary_rpc_method_handler(
                    servicer.jobs,
                    request_deserializer=job__runner__pb2.JobsRequest.FromString,
                    response_serializer=job__runner__pb2.JobsResponse.SerializeToString,
            ),
            'trigger': grpc.unary_unary_rpc_method_handler(
                    servicer.trigger,
                    request_deserializer=job__runner__pb2.TriggerRequest.FromString,
                    response_serializer=job__runner__pb2.TriggerResponse.SerializeToString,
            ),
            'abort': grpc.unary_unary_rpc_method_handler(
                    servicer.abort,
                    request_deserializer=job__runner__pb2.AbortRequest.FromString,
                    response_serializer=job__runner__pb2.AbortResponse.SerializeToString,
            ),
            'status': grpc.unary_unary_rpc_method_handler(
                    servicer.status,
                    request_deserializer=job__runner__pb2.StatusRequest.FromString,
                    response_serializer=job__runner__pb2.StatusResponse.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=job__runner__pb2.StatusStreamRequest.FromString,
                    response_serializer=job__runner__pb2.StatusUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'job_runner.RDSJobRunner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('job_runner.RDSJobRunner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RDSJobRunner(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/job_runner.RDSJobRunner/Ping',
            job__runner__pb2.PingRequest.SerializeToString,
            job__runner__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/job_runner.RDSJobRunner/execute',
            job__runner__pb2.ExecuteRequest.SerializeToString,
            job__runner__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def library(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/job_runner.RDSJobRunner/library',
            job__runner__pb2.LibraryRequest.SerializeToString,
            job__runner__pb2.LibraryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def jobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/job_runner.RDSJobRunner/jobs',
            job__runner__pb2.JobsRequest.SerializeToString,
            job__runner__pb2.JobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def trigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/job_runner.RDSJobRunner/trigger',
            job__runner__pb2.TriggerRequest.SerializeToString,
            job__runner__pb2.TriggerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/job_runner.RDSJobRunner/abort',
            job__runner__pb2.AbortRequest.SerializeToString,
            job__runner__pb2.AbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/job_runner.RDSJobRunner/status',
            job__runner__pb2.StatusRequest.SerializeToString,
            job__runner__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/job_runner.RDSJobRunner/StreamStatus',
            job__runner__pb2.StatusStreamRequest.SerializeToString,
            job__runner__pb2.StatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
